import { maxWidth, width } from "@mui/system";

export const styles = {
    container: {
      minHeight: "100vh",
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
      padding: "5%",
    },
    header: {
      width: "100%",
      textAlign: "left",
      color: "white",
      position: "absolute",
      top: { xs: "10px", sm: "30px", md: "25px", lg: "30px" },
      left: { xs: "10px", sm: "40px", md: "40px", lg: "50px" },
    },
    title: {
      fontWeight: "bold",
      marginTop: "0px",
      marginLeft: "2px",
      fontFamily: "Outfit",
      marginBottom: "10px",
      fontSize: { xs: "1.5rem", sm: "2.5rem", md: "3rem", lg: "3.7rem" },
    },
    subtitle: {
      marginTop: "0px",
      fontSize: { xs: "1rem", sm: "1rem", md: "1rem", lg: "1.1rem" },
      fontFamily: "Outfit",
      marginBottom: "10px",
    },
    imageContainer: {
      width: "100%",
      position: "absolute",
      top: { xs: "0rem", sm: "10rem", md: "8rem", lg: "8rem" },
      left: { xs: "0rem", sm: "-8rem", md: "-15rem", lg: "-18rem" },
    },
    image: {
      width: { xs: "60%", sm: "60%", md: "65%", lg: "75%" },
      maxWidth: "100%",
      height: "auto",
      zIndex: 1,
      transform: {
        xs: "scale(0.8)",
        sm: "scale(0.9)",
        md: "scale(1)",
        lg: "scale(1.1)",
      },
      transition: "transform 0.3s ease-in-out, width 0.3s ease-in-out",
    },
    exploreText: {
      fontFamily: "Outfit",
      fontWeight: "bold",
      textShadow: "2px 2px 4px rgba(0, 0, 0, 0.3)",
      fontSize: {
        xs: "clamp(1.2rem, 4vw, 1.5rem)",
        sm: "clamp(1.5rem, 4vw, 2rem)",
        md: "clamp(1.9rem, 3vw, 2.2rem)",
        lg: "clamp(2.3rem, 2.5vw, 2.4rem)",
      },
      textAlign: "center",
      marginBottom: { xs: "-10%", sm: "-20%", md: "-15%", lg: "-15%" },
      transition: "font-size 0.3s ease-in-out",
    },
    bestFoodsText: {
      fontWeight: "bold",
      fontFamily: "Outfit",
      textShadow: "2px 2px 4px rgba(0, 0, 0, 0.3)",
      fontSize: {
        xs: "clamp(1rem, 3.5vw, 1.25rem)",
        sm: "clamp(1.25rem, 3.5vw, 1.75rem)",
        md: "clamp(1.8rem, 3vw, 1.8rem)",
        lg: "clamp(1.5rem, 2.5vw, 1.6rem)",
      },
      textAlign: "center",
      transition: "font-size 0.3s ease-in-out",
    },
    bodyText: {
      fontFamily: "Outfit",
      fontSize: {
        xs: "clamp(0.7rem, 2.5vw, 0.8rem)",
        sm: "clamp(0.8rem, 2.5vw, 1rem)",
        md: "clamp(1rem, 2.5vw, 1rem)",
        lg: "clamp(0.7rem, 2.5vw, .9rem)",
      },
      textAlign: "center",
      transition: "font-size 0.3s ease-in-out",
    },
    loginBox: {
      width: { xs: "90%", sm: "50%", md: "35%", lg: "32%" },
      minHeight: "60vh",
      backgroundColor: "rgba(255, 255, 255, 0.4)",
      borderRadius: 6,
      padding: { xs: 2, sm: 3, md: 4 },
      marginLeft: { xs: "10px", sm: "280px", md: "500px", lg: "750px" },
      marginRight: { xs: "10px", sm: "40px", md: "80px", lg: "40px" },
      marginTop: { xs: "10px", sm: "80px", md: "40px", lg: "50px" },
      zIndex: 3,
    },
    welcomeText: {
      fontFamily: "Outfit",
      color: "#333",
      marginBottom: 2,
      textAlign: "center",
      fontWeight: "bold",
      fontSize: { xs: "1.5rem", sm: "2rem", md: "2.5rem", lg: "2.5rem" },
    },
    phoneInput: {
      backgroundColor: "white",
      maxWidth:'100%',
      height: "50px",
      borderRadius: "8px",
      boxShadow: "none",
      "& .MuiOutlinedInput-notchedOutline": { border: "none" },
      "& input": { fontFamily: "Outfit" },
      "& .MuiInputBase-input::placeholder": {
        fontFamily: "Outfit",
        textAlign: "left",
      },
    },
    CountryInput: {
        backgroundColor: "white",
        width:'100%',
        maxWidth:'250px',
        height: "50px",
        borderRadius: "8px",
        boxShadow: "none",
        "& .MuiOutlinedInput-notchedOutline": { border: "none" },
        "& input": { fontFamily: "Outfit" },
        "& .MuiInputBase-input::placeholder": {
          fontFamily: "Outfit",
          textAlign: "left",
        },
      },
    sendOtpButton: {
      background: "linear-gradient(to bottom, #FFDD44, #FF5500)",
      color: "#fff",
      marginBottom: 2,
      height: "45px",
      fontSize: { xs: "0.9rem", sm: "1rem", md: "1.1rem", lg: "1rem" },
      fontWeight: "normal",
      textTransform: "none",
    },
    orLoginText: {
      color: "#666",
      fontFamily: "Nunito",
      textAlign: "center",
      marginBottom: 2,
      position: "relative",
      fontSize: { xs: "0.8rem", sm: "0.9rem", md: "1rem", lg: "1.1rem" },
      "&::before, &::after": {
        content: '""',
        position: "absolute",
        top: "50%",
        backgroundImage: "url(Line.png)",
        backgroundSize: "cover",
        backgroundRepeat: "no-repeat",
        height: "1px",
        transform: "translateY(-50%)",
      },
      "&::before": { left: "0", right: "50%", width: "38%" },
      "&::after": { left: "62%", right: "0", width: "40%" },
    },
    socialLoginButton: {
      backgroundColor: "white",
      width: { xs: "100%", sm: "48%" },
      padding: 2,
      borderRadius: "8px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    createAccountText: {
      color: "#000000",
      fontFamily: "Outfit",
      textAlign: "center",
      fontSize: { xs: "0.8rem", sm: "0.9rem", md: "1rem", lg: "1.1rem" },
    },
    textContainer:{
        width: { xs: "90%", sm: "60%", md: "50%", lg: "30%" },
        position: "absolute",
        left: { xs: "5%", sm: "-8%", md: "-3%", lg: "12%" },
        bottom: { xs: "10px", sm: "10%", md: "8%", lg: "12%" },
        color: "#fff",
        zIndex: 3,
        margin: "0px auto",
        textAlign: "center",
    },
    homeContainer: {
        width: '100%',
        height: '100vh',
        position: 'relative',
        cursor: 'pointer',
      },
      contentBox: {
        textAlign: 'center',
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
      },
      Hometitle: {
        fontFamily: 'Outfit',
        color: 'white',
        fontSize: '70px',
        fontWeight: 'bold',
        marginBottom: 0,
      },
      Homesubtitle: {
        fontFamily: 'Outfit',
        color: 'white',
        marginTop: 0,
      },
  };
  
  